### ISSUE TITLE
Specific case stopping scripts

### ISSUE THREAD

**Issue by Undefined3301** [dyshay/Bot-Dofus-Retro#12]
_Hi there,_

There was a great improvement on map changing movements since the last release.
But it sounds like when somebody steals the ressource the bot is trying to collect, it sometimes makes the script stopping (maybe it targets the cell where the other guy is and stops the action).

![stealer-pausing](https://user-images.githubusercontent.com/26310745/67144015-74d22c00-f2a4-11e9-8ba6-be00c04ff911.png)

_**Could be related to #4 .**_

**Comment by dyshay** [comment]
Fixed in release 1.0.2-2
