### ISSUE TITLE
Problème de connexion 

### ISSUE THREAD

**Issue by nephelim2018** [dyshay/Bot-Dofus-Retro#15]
Impossible de choisir le personnage , le serveur Agathe qui et sur le bot et mal écrit ( qui doit être Algathe )

**Comment by grdlo** [comment]
Salut,

est-il possible de faire une 1.0.2-1 pour corriger ce léger problèmes présent depuis la 1.0.0 (j'ai testé chaque version) et qui bloque l'utilisation sur le serveur Algathe

**Comment by dyshay** [comment]
Je vais voir pour mettre ça en ligne rapidement
