### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: 'The Given key was no present in the dictionary.'

### ISSUE THREAD

**Issue by Undefined3301** [dyshay/Bot-Dofus-Retro#19]
_Hi there,_

**If this error appears, feel free to download the already-compiled version of the bot in the release section : https://github.com/Dyshay/Bot-Dofus-Retro/releases**.

If you still want to compile and run it by yourself : 

I suggest you to move "items", "mapas", "trayectos" folders (after unzipping them, they are on the root folder of the project) to the ./bin/Debug _(or Release)_ folder, you will find empty folder with the same name, it will bring the content they should contain to work properly 👍.

Peace&Bots 🤖

**Comment by dyshay** [comment]
I think add a message to user is good idea.
