### ISSUE TITLE
Doesn't work on Issering

### ISSUE THREAD

**Issue by Fortier006** [dyshay/Bot-Dofus-Retro#26]
Greetings!

I tried using the bot on Issering, but cannot manage to make it work. First, I saw Issering was not in the list of servers, so I decided to modify the combobox in the source code to add it. I did manage to make it connect  (as in, the program says I connected to the server successfully), but I cannot do anything else as I am stuck there. 

What am I doing wrong? How can I make it work on Issering? 

Thanks.

**Comment by dyshay** [comment]
Hi,
It turns out that this server was added not long ago that the others we will add it to the list
To be able to connect to this one, the server id must also be referenced

**Comment by jejaru** [comment]
Hi, I'm quite impressed with your work but I only have 2 tips:
1.You could explain step by step how to use the bot
2.I think the discord group is closed, open it so we can all help

**Comment by Undefined3301** [comment]
You can join the Discord server with this link until the repo one is updated 😃, you could ask questions in here : https://discord.gg/MAZg4Jd
