### ISSUE TITLE
Translate Source Code to English

### ISSUE THREAD

**Issue by DjTrilogic** [dyshay/Bot-Dofus-Retro#55]
Salut,

Je pense qu'un code écrit en anglais permettrait plus de collaboration sur ce projet.

De première vu le code est clair, propre. J'ai juste un peu de mal avec l'espagnol ^^

Btw, si y'a un discord ou un chat, peux-tu m'y inviter ? je suis grave chaud pour contribuer.

Merci

**Comment by Undefined3301** [comment]
Salut,

Le lien du Discord est disponible près du titre de la page principale du repo 😄 : https://discord.gg/PdvteG5

**Comment by dyshay** [comment]
#5 
Fait référence à cette issue
